---
- name: Copy initilisation script
  template:
    src: templates/credentials.groovy.j2
    dest: /var/lib/jenkins/init.groovy.d/0-credentials.groovy
    owner: jenkins
    group: jenkins
    mode: '0640'