---
- hosts: all
  gather_facts: yes
  vars_files:
    - vars/main.yml
  vars:
    ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.git
    - geerlingguy.ansible
    - geerlingguy.java
    - create-jenkins-user

- hosts: jenkins
  gather_facts: yes
  remote_user: jenkins
  vars_files:
    - vars/main.yml
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
  roles:
    - geerlingguy.jenkins
    - configure-jenkins-users
    - configure-jenkins-projects
  tasks:
    - name: retrieve jenkins public key
      command: cat /home/jenkins/.ssh/id_rsa.pub
      register: master_public_key
      changed_when: false

- hosts: agents
  gather_facts: yes
  remote_user: jenkins
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
  tasks:
    - name: add master public key to slaves
      authorized_key:
        user: jenkins
        key: "{{ hostvars['jenkins'].master_public_key.stdout }}"

# Jenkins private key has to be stored in Jenkins Credentials
# The client and server have to have their known_hosts updated
# The node then registered using the credentials