---
- hosts: all
  gather_facts: yes
  vars_files:
    - vars/main.yml
  vars:
    ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.git
    - geerlingguy.ansible
    - geerlingguy.java
    - create-jenkins-user

- hosts: jenkins
  gather_facts: yes
  remote_user: jenkins
  vars_files:
    - vars/main.yml
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
  roles:
    - geerlingguy.jenkins
    - configure-jenkins-users
    - configure-jenkins-credentials
    - configure-jenkins-projects
    - configure-jenkins-agents

- hosts: agents
  gather_facts: yes
  remote_user: jenkins
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
  roles:
    - configure-agent