---
- hosts: all
  gather_facts: yes
  vars_files:
    - vars/main.yml
  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.git
    - geerlingguy.ansible
    - geerlingguy.java

- hosts: jenkins
  gather_facts: yes
  vars_files:
    - vars/main.yml
  roles:
    - geerlingguy.jenkins
    - create-jenkins-users
    - create-jenkins-projects

- hosts: agents
  gather_facts: yes


